config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users

  resources :dashboard, only: :index
  resources :employees, only: :index

  resources :attendance, only: [] do
    collection do
      get :user_attendance_list
      get :today_attendance_list
      post :time_in
      post :time_out
    end
  end

  resources :dsr, only: [] do
    collection do
      get :add_dsr
      post :create_dsr
      get :send_dsr
      get :received_dsr
      post :fetch_send
      post :fetch_received
    end
    member do
      post :comments
      post :add_comment
    end
  end

  resources :report, only: [] do
    collection do
      get :add_report
      post :create_report
      get :send_report
      get :received_report
      post :fetch_send
      post :fetch_received
    end
  end

  resources :users, only: [] do
    collection do
      get :edit_profile
      post :remove_profile_picture
      post :change_password
      post :profile_picture
    end
  end

  defaults format: :json do
    namespace :api do
      namespace :v1 do
        resources :sessions, only: [:create] do
          match '/', to: 'sessions#destroy', via: 'delete', on: :collection
        end
        resources :sessions, only: [:index]
        resources :dashboard, only: [:index]
        resources :projects, only: [:index] do
          collection do
            get :assigned_projects
          end
        end
        resources :attendances, only: [:index] do
          collection do
            post :time_in
            post :time_out
          end
        end

        resources :employees, only: [] do
          collection do
            get :get_all_user
          end
        end

        resources :daily_status, only: [] do
          collection do
            post :add_dsr
            get :send_list
            get :received_list
          end
          member do
            get :fetch_send
            get :fetch_received
            get :comments
            post :add_comment
          end
        end

        resources :weekly_status, only: [] do
          collection do
            post :add_report
            get :send_list
            get :received_list
          end
          member do
            get :fetch_send
            get :fetch_received
          end
        end

        match '*unmatched', to: 'base#route_not_found', via: :all
      end
    end
  end

  root "dashboard#index"
end

app/views/layouts/shared/_flash_message.html.erb
<div id="flash-message" data-controller="flash" data-flash-target="message">
  <% if type == 'success' %>
    <div class="alert alert-success ajax-success-alert" style="display: block">
      <a href="javascript:void(0)" class="close ml-4" data-action="click->flash#remove">&times;</a>
      <span class="ajax-success-alert-message"><%= message %></span>
    </div>
  <% elsif type == 'error' %>
    <div class="alert alert-danger ajax-danger-alert" style="display: block">
      <a href="javascript:void(0)" class="close ml-4" data-action="click->flash#remove">&times;</a>
      <span class="ajax-danger-alert-message"><%= message %></span>
    </div>
  <% elsif type == 'warning' %>
    <div class="alert alert-warning ajax-warning-alert" style="display: block">
      <a href="javascript:void(0)" class="close ml-4" data-action="click->flash#remove">&times;</a>
      <span class="ajax-warning-alert-message"><%= message %></span>
    </div>
  <% end %>
</div>

app/views/layouts/shared/_footer.html.erb
<footer class="footer w-100">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-lg-between">
      <div class="copyright text-center text-sm text-muted text-lg-start">
        © <%= Date.today.year %> ,
        <%= link_to("Talentelgia Technology", "https://www.talentelgia.com", class: "font-weight-bold", target: "_blank") %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= turbo_stream_from "flash-#{current_user.encrypted_id}-flash-message" %>
      <div id="flash-<%= current_user.encrypted_id %>-flash-message">
        <% flash.each do |type, message| %>
          <%= render partial: 'layouts/shared/flash_message', locals: { type: type, message: message } %>
        <% end %>

      </div>

      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  mr-md-auto">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark"
               data-action="sidenav-pin"
               data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center ml-auto ml-md-0 "
          data-user-display-class="show"
          data-action="user:click:outside->user#hideUserDropdown"
          data-controller="user">
          <li class="nav-item dropdown"
              data-user-target="user">
            <a class="nav-link pr-0"
               href="javascript:void(0);"
               role="button"
               data-action="click->user#showUserDropdown">
              <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <% if current_user&.profile_picture.present? %>
                  <%= image_tag(current_user.profile_picture_url(:thumb), alt: "filename", class: "header-image") %>
                <% else %>
                  <%= image_tag("sidebar_image.png", class: "header-image", alt: "preview") %>
                <% end%>

              </span>
                <div class="media-body  ml-2  d-none d-lg-block">
                  <span class="mb-0 text-sm  font-weight-bold"><%= current_user.full_name %></span>
                </div>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right"
                 data-user-target="dropdown">
              <div class="dropdown-header noti-title">
                <h6 class="text-overflow m-0">Welcome!</h6>
              </div>
              <%= link_to(edit_profile_users_path, class: "dropdown-item") do %>
                <i class="fas fa-user"></i>
                <span>Edit profile</span>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= button_to(destroy_user_session_path, {class: "dropdown-item",method: :delete}) do %>
                <i class="fa fa-sign-out" aria-hidden="true"></i>
                <span>Logout</span>
              <% end %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_side_menu.html.erb
<% if node.present? %>
  <% if node.nodes.count > 0 %>
    <li class="nav-item submenu<%= (controller_name.eql?(node.controller)) ? ' active' : '' %>">
      <a href="javascript:void(0)" class="nav-link submenu-toggle">
        <i class="sidenav-icon <%= node['icon'] if node['icon'].present? %>"></i>
        <span><%= node['name'].html_safe %></span>
        <i class="fas fa-caret-right ml-auto fa-caret-down"></i>
      </a>
      <ul>
        <% node.nodes.order("position ASC").each do |child_node| %>
          <%= render partial: "layouts/shared/side_menu", locals: { node: child_node, sub_node: true } %>
        <% end %>
      </ul>
    </li>
  <% else %>
    <% if sub_node %>
      <li class="<%= (controller_name.eql?(node.controller) && action_name.eql?(node.action)) ? ' sub-active' : '' %>">
        <%= link_to url_for(controller: "#{node.controller}", action: "#{node.action}"), data: {action: "click->node#startLoader"} do %>
          <i class="<%= node.icon if node.icon.present? %>"></i>
          <span class="nav-link-text"><%= node.name.html_safe %></span>
        <% end %>
      </li>
    <% else %>
      <li class="nav-item<%= (controller_name.eql?(node.controller) && action_name.eql?(node.action)) ? ' active' : '' %>">
        <%= link_to url_for(controller: "#{node.controller}", action: "#{node.action}"), class: "nav-link", data: {action: "click->node#startLoader"} do %>
          <i class="<%= node.icon if node.icon.present? %>"></i>
          <span class="nav-link-text"><%= node.name.html_safe %></span>
        <% end %>
      </li>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/shared/_sidebar.html.erb
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <div class="sidenav-header  align-items-center">
      <%= link_to("/", class: "navbar-brand") do %>
        <%= image_tag("tt-one.svg", class: "navbar-brand-img", alt: "...") %>
      <% end %>
    </div>
    <div>
      <span class="close_sidebar"><i class="fa fa-times"></i></span>
    </div>
    <div class="navbar-inner">
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <ul class="navbar-nav" data-controller="node">
          <% @nodes.each do |node| %>
            <% if node.count > 0 %>
              <%= render partial: "layouts/shared/side_menu", locals: {node: node, sub_node: false} %>
            <% end %>
          <% end if @nodes.present? %>
        </ul>
      </div>
    </div>
  </div>
</nav>