config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users

  resources :dashboard, only: :index
  resources :employees, only: :index

  resources :attendance, only: [] do
    collection do
      get :user_attendance_list
      get :today_attendance_list
      post :time_in
      post :time_out
    end
  end

  resources :dsr, only: [] do
    collection do
      get :add_dsr
      post :create_dsr
      get :send_dsr
      get :received_dsr
      post :fetch_send
      post :fetch_received
    end
    member do
      post :comments
      post :add_comment
    end
  end

  resources :report, only: [] do
    collection do
      get :add_report
      post :create_report
      get :send_report
      get :received_report
      post :fetch_send
      post :fetch_received
    end
  end

  resources :users, only: [] do
    collection do
      get :edit_profile
      post :remove_profile_picture
      post :change_password
      post :profile_picture
    end
  end

  defaults format: :json do
    namespace :api do
      namespace :v1 do
        resources :sessions, only: [:create] do
          match '/', to: 'sessions#destroy', via: 'delete', on: :collection
        end
        resources :sessions, only: [:index]
        resources :dashboard, only: [:index]
        resources :projects, only: [:index] do
          collection do
            get :assigned_projects
          end
        end
        resources :attendances, only: [:index] do
          collection do
            post :time_in
            post :time_out
          end
        end

        resources :employees, only: [] do
          collection do
            get :get_all_user
          end
        end

        resources :daily_status, only: [] do
          collection do
            post :add_dsr
            get :send_list
            get :received_list
          end
          member do
            get :fetch_send
            get :fetch_received
            get :comments
            post :add_comment
          end
        end

        resources :weekly_status, only: [] do
          collection do
            post :add_report
            get :send_list
            get :received_list
          end
          member do
            get :fetch_send
            get :fetch_received
          end
        end

        match '*unmatched', to: 'base#route_not_found', via: :all
      end
    end
  end

  root "dashboard#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_paper_trail #make versions of any event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :validatable

  validates_presence_of :first_name
  enum role: %i[employee manager super_admin hr], _default: "employee"
  enum status: %i[active inactive terminated], _default: "active"
  mount_uploader :profile_picture, ImageUploader

  has_many :users_projects, dependent: :destroy
  has_many :daily_statuses, dependent: :destroy
  has_many :weekly_statuses, dependent: :destroy
  has_many :attendance_reports, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :projects, through: :users_projects
  belongs_to :department
  belongs_to :designation

  def full_name
    [first_name, last_name].join(" ").strip
  end

  def start_working
    self.attendance_reports.today_attendances.last
  end

  def self.upcoming_birthdays(limit = 5)
    start_month = Date.today.month
    start_day = Date.today.day
    end_month = 12
    end_day = 31
    users = User.where("(DATE_PART('month', dob) >= ? AND DATE_PART('day', dob) >= ?) AND (DATE_PART('month', dob) <= ? AND DATE_PART('day', dob) <= ?)", start_month, start_day, end_month, end_day).limit(limit)
    users_data = users.order(Arel.sql("DATE_PART('month', dob), DATE_PART('day', dob)"))
    return users_data if users_data.count == limit
    start_month = 1
    start_day = 1
    end_month = (Date.today - 1.month).month
    end_day = (Date.today - 1.month).end_of_month.day
    if end_month != 12
      users = User.where("(DATE_PART('month', dob) >= ? AND DATE_PART('day', dob) >= ?) AND (DATE_PART('month', dob) <= ? AND DATE_PART('day', dob) <= ?)", start_month, start_day, end_month, end_day).limit(limit - users_data.count)
      users_data += users.order(Arel.sql("DATE_PART('month', dob), DATE_PART('day', dob)"))
      return users_data if users_data.count == limit
    end
    start_month = 1
    start_day = end_month
    end_month = Date.today.month
    end_day = Date.today.day - 1
    users = User.where("(DATE_PART('month', dob) >= ? AND DATE_PART('day', dob) >= ?) AND (DATE_PART('month', dob) <= ? AND DATE_PART('day', dob) <= ?)", start_month, start_day, end_month, end_day).limit(limit - users_data.count)
    users_data = users_data + users.order(Arel.sql("DATE_PART('month', dob), DATE_PART('day', dob)"))
    users_data.uniq
  end

end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersConcern
  skip_before_action :build_node, except: :edit_profile

  def edit_profile

  end

  def change_password
    if current_user.valid_password?(password_params[:current_password])
      if current_user.update_with_password(password_params)
        @success = "Password Changed Successfully."
        bypass_sign_in(current_user)
      else
        @errors = "something went wrong!"
      end
    else
      @errors = "Current Password does not match.\n"
    end
  end

  def remove_profile_picture
    current_user.profile_picture = nil
    if current_user.save
      redirect_to edit_profile_users_path
    else
      broadcast_flash_message("error", "Something Went Wrong.")
      render edit_profile
    end
  end

  def profile_picture
    current_user.assign_attributes(profile_picture_params)
    if current_user.save
      flash[:success] = "Profile picture changed successfully."
      redirect_to edit_profile_users_path
    else
      broadcast_flash_message("error", "Something Went Wrong.")
      render edit_profile
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_change_password.html.erb
<div class="card">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col-8">
        <h3 class="mb-0">Edit profile </h3>
      </div>
    </div>
  </div>
  <div class="card-body" data-controller="validation">
    <%= form_for current_user, as: :change_password, url: { controller: request[:controller], action: :change_password }, method: :post, remote: true do |f| %>
      <h6 class="heading-small text-muted mb-4">Change password</h6>
      <div class="">
        <% if @success %>
          <div class="mb-3">
            <span class="text-success"><%= @success %></span>
          </div>
        <% end %>
        <% if @errors %>
          <div class="mb-3">
            <span class="text-danger"><%= @errors %></span>
          </div>
        <% end %>
        <div class="row">
          <div class="col-lg-12">
            <div class="form-group">
              <label class="form-control-label" for="old_password">Current Password</label>
              <%= f.password_field(:current_password, placeholder: "Current password", class: "required form-control", data: { target: "validation.currentPassword" }) %>
              <span class="text-danger" data-validation-target="currentPasswordSpan"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <label class="form-control-label" for="new_password">New Password</label>
              <%= f.password_field(:password, placeholder: "New password", class: "required form-control", data: { target: "validation.newPassword" }) %>
              <span class="text-danger" data-validation-target="newPasswordSpan"></span>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form-group">
              <label class="form-control-label" for="confirm_password">Confirm Password</label>
              <%= f.password_field(:confirm_password, placeholder: "Confirm password", class: "required form-control", data: { target: "validation.confirmPassword" }) %>
              <span class="text-danger" data-validation-target="confirmPasswordSpan"></span>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit(:Update, class: "btn  btn-info  mr-4  add-user-btn", data: { action: "click->validation#validate" }) %>
    <% end %>
  </div>
</div>

app/views/users/change_password.js.erb
$('#loader-body').fadeOut();
$("#change-password-div").html("<%= j render(partial: "users/change_password", locals: { errors: @errors, current_user: current_user}) %>");

app/views/users/edit_profile.html.erb
<div class="header pb-8 d-flex align-items-center" style="background-size: cover; background-position: center top;">
  <span class="mask bg-gradient-default opacity-8"></span>
</div>

<div class="container-fluid mt--6" data-controller="loader">
  <div class="row">
    <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <%= image_tag("profile-background.jpg", alt: "Image placeholder", class: "card-img-top") %>
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <% if current_user&.profile_picture_url.present? %>
                <%= image_tag(current_user.profile_picture_url, alt: "", class: "img-upload-preview rounded-circle") %>
              <% else %>
                <%= image_tag("no-image.png", alt: "preview", class: "img-upload-preview rounded-circle") %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          <%= form_for current_user, as: :profile, url: { controller: request[:controller], action: :profile_picture }, class: "d-flex justify-content-between align-items-start", method: :post do |f| %>
            <%= f.file_field(:profile_picture, class: "form-control-file valImage", accept: ".jpg, .jpeg, .png") %>
            <%= f.submit("Upload Profile Picture", class: "btn btn-sm btn-info", data: { action: "click->loader#startLoader" }) %>
          <% end %>
          <div class="text-left">
            <%= link_to(remove_profile_picture_users_url, data: { action: "click->loader#startLoader" }, method: :post) do %>
              <span>Remove Picture</span>
            <% end if current_user&.profile_picture.present? %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-8 order-xl-1" id="change-password-div">
      <%= render partial: "users/change_password", locals: { errors: nil, current_user: current_user} %>
    </div>
  </div>
</div>