config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  devise_for :users

  resources :dashboard, only: :index
  resources :employees, only: :index

  resources :attendance, only: [] do
    collection do
      get :user_attendance_list
      get :today_attendance_list
      post :time_in
      post :time_out
    end
  end

  resources :dsr, only: [] do
    collection do
      get :add_dsr
      post :create_dsr
      get :send_dsr
      get :received_dsr
      post :fetch_send
      post :fetch_received
    end
    member do
      post :comments
      post :add_comment
    end
  end

  resources :report, only: [] do
    collection do
      get :add_report
      post :create_report
      get :send_report
      get :received_report
      post :fetch_send
      post :fetch_received
    end
  end

  resources :users, only: [] do
    collection do
      get :edit_profile
      post :remove_profile_picture
      post :change_password
      post :profile_picture
    end
  end

  defaults format: :json do
    namespace :api do
      namespace :v1 do
        resources :sessions, only: [:create] do
          match '/', to: 'sessions#destroy', via: 'delete', on: :collection
        end
        resources :sessions, only: [:index]
        resources :dashboard, only: [:index]
        resources :projects, only: [:index] do
          collection do
            get :assigned_projects
          end
        end
        resources :attendances, only: [:index] do
          collection do
            post :time_in
            post :time_out
          end
        end

        resources :employees, only: [] do
          collection do
            get :get_all_user
          end
        end

        resources :daily_status, only: [] do
          collection do
            post :add_dsr
            get :send_list
            get :received_list
          end
          member do
            get :fetch_send
            get :fetch_received
            get :comments
            post :add_comment
          end
        end

        resources :weekly_status, only: [] do
          collection do
            post :add_report
            get :send_list
            get :received_list
          end
          member do
            get :fetch_send
            get :fetch_received
          end
        end

        match '*unmatched', to: 'base#route_not_found', via: :all
      end
    end
  end

  root "dashboard#index"
end

app/controllers/dsr_controller.rb
class DsrController < ApplicationController
  skip_before_action :build_node, except: [:add_dsr, :send_dsr, :received_dsr]
  include DsrConcern
  helper "dsr"

  # add new dsr function which initialize object for dsr
  def add_dsr
    @dsr = current_user.daily_statuses.new
    @dsr.daily_status_reports.build
    @dsr.documents.build
    @assigned_projects = current_user.projects
  end

  # create  function which create new dsr
  def create_dsr
    @assigned_projects = current_user.projects
    @dsr = current_user.daily_statuses.new(dsr_params)
    if @dsr.save
      flash[:success] = "Dsr send successfully."
      redirect_to :send_dsr_dsr_index
    else
      broadcast_flash_message("error", "Dsr not create.")
    end
  end

  # get list of sending dsr's of current users
  def send_dsr
    dsrs = current_user.daily_statuses.order("created_at DESC")
    @pagy, @dsrs = pagy(dsrs, link_extra: 'data-remote="true" data-action="click->dsr#startLoader"')
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  # get list of received dsr's for current users
  def received_dsr
    dsrs = DailyStatus.includes(:daily_status_reports).received(current_user.id).order("created_at DESC")
    @pagy, @dsrs = pagy(dsrs, link_extra: 'data-remote="true" data-action="click->dsr#startLoader"')
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def fetch_received
    @dsr = DailyStatus.received(current_user.id).find(params[:id])
    respond_to do |format|
      format.html { render partial: "dsr/dsr_detail", locals: { dsr: @dsr, current_user: current_user }, layout: false }
      format.js { render layout: false }
    end
  end

  def fetch_send
    @dsr = current_user.daily_statuses.includes(:daily_status_reports).find(params[:id])
    respond_to do |format|
      format.html { render partial: "dsr/dsr_detail", locals: { dsr: @dsr, current_user: current_user }, layout: false }
      format.js { render layout: false }
    end
  end

  def comments
    @dsr = DailyStatus.received(current_user.id).or(current_user.daily_statuses).find(params[:id])
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def add_comment
    @dsr = DailyStatus.received(current_user.id).or(current_user.daily_statuses).find(params[:id])
    @comment = @dsr.comments.new(dsr_comment_params)
    if @dsr.save
      respond_to do |format|
        format.js { render layout: false }
      end
    else
      flash[:alert] = "Failed to add comment."
      render :add_dsr
    end
  end

end

app/helpers/dsr_helper.rb
module DsrHelper

  def get_total_time(time_difference)
    time = ""
    if time_difference.present?
      difference = Time.at(time_difference).utc
      day, hour, mint = difference.strftime("%d-%H-%M").split("-")
      hour = day.to_i > 1 ? (hour.to_i + ((24 * day.to_i) - 24)) : hour
      if hour.to_i > 0
        time = "#{hour.to_i} Hr#{hour.to_i > 1 ? 's' : ''}"
      end
      if mint.to_i > 0
        time = "#{time ? time + " " : ""}#{mint} Mins"
      end
    end
    time
  end

end

app/views/dsr/_comment.html.erb
<div data-controller="dsrcomment"
     data-dsrcomment-target="currentDiv">
  <%= hidden_field_tag("user_id", current_user.encrypted_id, data: {target: "dsrcomment.userId"}) %>
  <%= hidden_field_tag("comment_id", comment.id, data: {target: "dsrcomment.commentId"}) %>
</div>

<div id="comment-dsr-<%= comment.id %>" class="<%= comment.user_id === current_user.id ? "text-right receiver" : "text-left sender" %> mb-2" id="new-comment">
  <h5><b><%= current_user.full_name %></b></h5>
  <p style="margin-bottom:0px">
    <%= comment.comment %>
  </p>
  <p>
    <small>
      <i>
        <% created_at = comment.created_at %>
        <% date = created_at.to_formatted_s(:long_ordinal).split(",").first %>
        <%= created_at.strftime("#{date} %Y, %l:%M pm") %>
      </i>
    </small></p>
</div>
<div id="dsr-new-comments-<%= dsr.encrypted_id %>-<%= dsr.user_id %>"></div>

app/views/dsr/_comment_form.html.erb
<%#= turbo_stream_from dom_id(current_user, :broadcast_to) %>
<div id="comments-modal" class="modal show" role="dialog" style="display: block">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">Comments</h3>
        <button type="button" class="close" data-action="click->dsr#closeModal">&times;</button>
      </div>

      <div class="modal-body" id="dsr-comments-body-<%= dsr.id %>-<%= dsr.user_id %>">
        <%= turbo_stream_from dsr %>
          <% if dsr.comments.present? %>
            <% users_data = {} %>
            <% users_data[current_user.id] = current_user.full_name %>
            <% dsr.comments.map do |comment| %>
                <% unless users_data[comment.user_id] %>
                  <% users_data[comment.user_id] = comment.user&.full_name || "N-A" %>
                <% end %>
                <div id="comment-dsr-<%= comment.encrypted_id %>" class="<%= comment.user_id === current_user.id ? "text-right receiver" : "text-left sender" %> mb-2">
                  <h5><b><%= users_data[comment.user_id] %></b></h5>
                  <p style="margin-bottom: 0px">
                    <%= comment.comment %>
                  </p>
                  <p>
                    <small>
                      <i>
                        <% created_at = comment.created_at %>
                        <% date = created_at.to_formatted_s(:long_ordinal).split(",").first %>
                        <%= created_at.strftime("#{date} %Y, %l:%M pm") %>
                      </i>
                    </small></p>
                </div>
            <% end %>
          <div id="dsr-new-comments-<%= dsr.encrypted_id %>-<%= dsr.user_id %>">
          </div>
          <% else %>
          <div id="dsr-new-comments-<%= dsr.encrypted_id %>-<%= dsr.user_id %>">
            <h4 class="text-center">
              There are no comments present for this DSR.
            </h4>
          </div>
          <% end %>
        </div>
      <div class="modal-footer">
        <div class="w-100">
          <% comment = dsr.comments.new %>
          <%= form_for(comment, as: :dsr_comment, url: { controller: request[:controller], action: :add_comment }, remote: true, method: :post, class: "w-100") do |f| %>
            <%= f.text_area(:comment, placeholder: "Write a comment...", class: " form-control scroll", id: "dsr-comments-text-#{dsr.id}-#{dsr.user_id}") %>
            <div class="text-right">
              <%= f.submit(:submit, value: "Add", class: "btn btn-primary mt-3 add_comment") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dsr/_dsr.html.erb
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item">
                <%= link_to("/") do %>
                  <i class="fas fa-home"></i>
                <% end %>
              </li>
              <li class="breadcrumb-item active" aria-current="page">DSR</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid dsr-detail-pg mt--6" data-controller="dsr">
  <div class="row" id="dsr_list_view">
    <div class="col-6">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center border-0">
          <h3 class="mb-0">DSR List</h3>
          <span class="w-75">
            <input placeholder="Search by description and project name"
                   type="text"
                   id="searchDsr"
                   name="search_dsr"
                   class="form-control" />
          </span>
        </div>
        <div id="dsr-table-div">
          <%= render partial: "dsr/dsr_list", locals: { dsrs: dsrs, pagy: pagy, current_user: current_user} %>
        </div>
      </div>
    </div>
    <div class="col-6"  id="dsr_detail_view" data-dsr-target="detail_view">
      <%= render partial: "dsr/dsr_detail", locals: { dsr: dsr, current_user: current_user} %>
    </div>
  </div>
  <div id="dsr-comments"></div>
</div>

app/views/dsr/_dsr_detail.html.erb
<% if dsr.present? %>
  <div class="card">
    <div class="card-header d-flex justify-content-between align-items-center border-0">
      <h3 class="mb-0">DSR Details</h3>
    </div>
    <div class="card-body">
      <div class="canvas-wrapper dsr-details-content">
        <% project_hash = {} %>
        <% project_hash[""] = "N-A" %>
        <% last_project_id = 0, index_value = 0 %>
        <% total_time = 0 %>
        <% dsr.daily_status_reports.each do |report_detail| %>
          <% total_time += report_detail.time_difference %>
          <% project_id = report_detail.project_id.to_s %>
          <% unless project_hash[project_id].present? %>
            <% project_hash[project_id] = report_detail.project&.name || 'N-A' %>
          <% end %>

          <% if last_project_id != project_id %>
            <div class="row">
              <div class="col-12">
                <h4 class="mb-3">Project: <%= project_hash[project_id] %></h4>
              </div>
            </div>
            <% last_project_id = project_id %>
            <% index_value = 0 %>
          <% end %>
          <div class="row mb-4 dsr-details-list">
            <div class="col-xl-12">
              <h5><%= index_value += 1 %>. <%= report_detail.task.to_s %></h5>
              <div class="time_estimate">
                <p class="m-0 text-left">
                  <strong>Time: </strong>
                  <%= report_detail.start_time&.strftime("%I:%M %p") %>
                  - <%= report_detail.end_time&.strftime("%I:%M %p") %>
                </p>
                <p class="m-0 text-right">
                  <strong>Time Estimate: </strong><%= report_detail.total_time %>
                </p>
              </div>
              <pre class="m-0"><%= report_detail.description.to_s %></pre>
            </div>
          </div>
        <% end %>
        <div class="estimated-total--time"><strong>Total Time Estimate:</strong>  <%= get_total_time(total_time) %></div>
        <b>Attachments: </b>
        <% if dsr.documents.present? %>
          <% dsr.documents.each do |attachment| %>
            <br>
            <%= link_to(attachment.file.file.original_filename, url_for(attachment.file_url), download: true) %>
          <% end %>
        <% else %>
          N-A
        <% end %>
      </div>
    </div>
    <!-- Card footer -->
    <div class="card-footer py-3 px-3">
      <div class="row">
        <div id="sent-details-data" class="col-sm-6" style="cursor: pointer" data-action="click->dsr#toggleDetail">
          See Details
          <div id="sent-details" style="display: none;" class="mt-2" data-dsr-target="send_detail">
            <% if dsr.present? %>
              <b>To: </b><%= User.where(id: dsr.to_ids).pluck(:email).join(", ") %>
              <br>
              <% if dsr.cc_ids.present? %>
                <b>Cc: </b><%= User.where(id: dsr.cc_ids).pluck(:email).join(", ") %>
              <% end %>
            <% end %>
          </div>
        </div>
        <%= link_to(comments_dsr_path(dsr), class: "col-sm-6 text-right", remote: true, method: :post, style: "color: black") do %>
          Add Comment
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/dsr/_dsr_form.html.erb
<div class="table input-lists">
  <% status_report = DailyStatus.new %>
  <% status_report.daily_status_reports.build %>
  <% status_report.documents.build %>
  <%= form_for status_report, as: :dsr, url: { controller: request[:controller], action: :create_dsr }, method: :post do |f| %>
    <template data-dsr-target='new_project_task'>
      <%= f.fields_for :daily_status_reports, child_index: 'NEW_PROJECT_TASK' do |daily_status_report| %>
        <%= render partial: 'dsr/report_detail_fields', locals: { daily_status_report: daily_status_report, f: f, is_new: false, add_sub: true, assigned_projects: @assigned_projects, project_id: daily_status_report.object.project_id } %>
      <% end %>
    </template>

    <template data-dsr-target='new_task'>
      <%= f.fields_for :daily_status_reports, child_index: 'NEW_TASK' do |daily_status_report| %>
        <%= render partial: 'dsr/report_detail_fields', locals: { daily_status_report: daily_status_report, f: f, is_new: false, add_sub: false, assigned_projects: @assigned_projects, project_id: daily_status_report.object.project_id } %>
      <% end %>
    </template>

    <template data-dsr-target='newDocument'>
      <%= f.fields_for :documents, child_index: 'NEW_DSR_DOCUMENT' do |p| %>
        <div id="remove-document-div">
          <%= p.file_field :file, multiple: false, accept: '.jpg, .jpeg, .png, .doc, .docx, .pdf, .xlsx, .csv' %>
          <span class="remove-document-button">
              <%= link_to("javascript:void(0)", class: "btn btn-danger btn-md document-btn", data: { action: "click->dsr#removeDocument" }) do %>
                Remove Attachment
              <% end %>
            </span>
        </div>
      <% end %>
    </template>

  <% end %>
  <%= form_for @dsr, as: :dsr, url: { controller: request[:controller], action: :create_dsr }, method: :post do |f| %>
    <%= f.fields_for :daily_status_reports do |daily_status_report| %>
      <%= render partial: 'dsr/report_detail_fields', locals: { daily_status_report: daily_status_report, f: f, is_new: true, add_sub: true, assigned_projects: @assigned_projects, project_id: daily_status_report.object.project_id } %>
    <% end %>

    <small data-dsr-target="add_item"></small>

    <br/>
    <div>
      <div id="add-document-div">
        <label><b>Attachments: </b></label>
        <small>
          <%= link_to("javascript:void(0)", class: "btn btn-primary btn-md document-btn", data: { action: "click->dsr#addDocument" }) do %>
            Add Attachment
          <% end %>
        </small>
      </div>
      <%= f.fields_for :documents do |p| %>
        <div id="remove-document-div">
          <%= p.file_field :file, multiple: false, accept: '.jpg, .jpeg, .png, .doc, .docx, .pdf, .xlsx, .csv' %>
          <span class="remove-document-button">
            <%= link_to("javascript:void(0)", class: "btn btn-danger btn-md document-btn", data: { action: "click->dsr#removeDocument" }) do %>
              Remove Attachment
            <% end %>
          </span>
        </div>
      <% end %>
      <small data-dsr-target="documentList"></small>
      <br>
      <small><b>*Note:</b> Only .jpg, .jpeg, .png, .doc, .docx, .pdf, .xlsx and .csv formats are allowed.</small>
    </div>


    <br>
    <div id="send_to">
      <label><b>Send To:</b></label> &nbsp
      <% to_ids = f.object.to_ids rescue [] %>
      <% User.manager.or(User.super_admin).order(:first_name).each do |user| %>
        <% next if current_user.id == user.id %>
        <%= f.check_box :to_ids, { multiple: true, disabled: !!user.super_admin? }, user.id, (user.super_admin? || to_ids.include?(user.id)) %>
        <%= user.full_name %>
      <% end %>
    </div>
    <br>
    <div class="button-group ">
      <% cc_ids = f.object.cc_ids rescue [] %>
      <label><b>Add Cc:</b></label> &nbsp
      <% User.hr.or(User.employee).order(:first_name).each do |user| %>
        <% next if current_user.id == user.id %>
        <%= f.check_box :cc_ids, { multiple: true, disabled: !!user.super_admin? }, user.id, (user.super_admin? || cc_ids.include?(user.id)) %>
        <%= user.full_name %>
      <% end %>
    </div>
    <br/>
    <div class="subbtn">
      <%= f.submit "Submit DSR", class: "btn btn-primary  pull-center", data: { action: "click->dsr#validate" } %>
    </div>

  <% end %>
</div>

app/views/dsr/_dsr_list.html.erb
<div class="card-body">
  <div class="canvas-wrapper dsr-details-list">
    <div class="table-responsive">
      <div>
        <%= image_tag("small_loader.gif", class: "loaderList",style: "display: none; margin-left: 35%; margin-right: 30%; width: 10%;" ) %>
      </div>
      <table class="table ">
        <tbody id="dsr_tbody">
        <% dsrs.each do |dsr| %>
          <% project_hash = {} %>
          <% project_hash[""] = "N-A" %>
          <% user_hash = {} %>
          <% user_hash[""] = "N-A" %>
          <% daily_status_report = dsr.daily_status_reports.first %>
          <tr class="dsr-point"
              id="dsr-<%= dsr.id %>"
              data-action="click->dsr#<%= current_user.id == dsr.user_id ? "fetchSendDsr" : "fetchReceivedDsr" %>"
              data-dsr-id-param="<%= dsr.id %>">
            <% project_id = daily_status_report.project_id.to_s %>
            <% unless project_hash[project_id].present? %>
              <% project_hash[project_id] = daily_status_report.project&.name || 'N-A' %>
            <% end %>
            <% if current_user.id != dsr.user_id %>
              <td width="20%">
                <% user_id = dsr.user_id.to_s %>
                <% unless user_hash[user_id].present? %>
                  <% user_hash[user_id] = dsr.user.full_name %>
                <% end %>
                <b><%= user_hash[user_id] %></b>
              </td>
              <td width="50%">
                <b><%= project_hash[project_id] || "N-A" %></b><br>
                <%= daily_status_report&.description.to_s.truncate_bytes(50) %>...
              </td>
            <% else %>
              <td width="70%">
                <b><%= project_hash[project_id] || "N-A" %></b><br>
                <%= daily_status_report&.description.to_s.truncate_bytes(50) %>...
              </td>
            <% end %>
            <td width="30%"><%= dsr.date.strftime('%d-%m-%Y') || "-" %></td>
          </tr>
        <% end if dsrs.present? %>
        <% unless dsrs.present? %>
        <tr>
          <td colspan="3" class="no_record">
            <span><b>No records found</b></span>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
      <span class="paginate-content">
        <%= raw pagy_nav(pagy) if pagy.pages > 1 %>
      </span>
    </div>
  </div>
</div>

app/views/dsr/_report_detail_fields.html.erb
<% if add_sub %>
  <div id="<%= project_id || 0 %>">
    <table class="nested-dsr-fields" width="100%">
      <thead width="100%">
      <tr>
        <td colspan="3">
          <%= daily_status_report.select("project_id", options_for_select((assigned_projects.collect { |u| [u.name, u.id] }).concat([["Other", 0]]), (daily_status_report.object.project_id rescue nil)), { include_blank: "Select Project" }, { class: "form-control dsr select-project", required: true }) %>
        </td>
        <td width="10%">
          <% if is_new %>
            <small>
              <%= link_to("javascript:void(0)", class: "btn btn-primary btn-md btn-circle add-rows", data: { action: "click->dsr#add_association", "item-id-param" => "12345" }) do %>
                <i class="fa fa-plus" aria-hidden="true"></i>
              <% end %>
            </small>
          <% elsif daily_status_report&.object&.id.nil? %>
            <small>
              <%= link_to("javascript:void(0)", class: "btn btn-danger btn-md delRow btn-circle", data: { action: "click->dsr#remove_association" }, :"data-item-id-param" => "12345") do %>
                <i class="fa fa-times"></i>
              <% end %>
            </small>
          <% end %>
        </td>
      </tr>
      </thead>
      <tbody id="nested-sub-fields" class="sub-table-body">
      <tr id="tr-1">
        <%= daily_status_report.hidden_field :_destroy %>
      </tr>
      <tr id="tr-2">
        <td width="70%">
            <%= daily_status_report.text_field :task, placeholder: "Task", class: "form-control dsr", required: true, data: { target: "dsr.task", action: "blur->dsr#validateValue" } %>
            <span class="text-danger"></span>
        </td>

        <td width="10%">
            <%= daily_status_report.text_field :start_time, value: "#{daily_status_report&.object&.start_time&.strftime("%H:%M") rescue ''}",
                                         placeholder: "Start Time",
                                         class: "form-control start_time timer timeEst timer",
                                         required: true, readonly: true, data: { target: "dsr.startTime", action: "blur->dsr#validateValue" } %>
            <span class="text-danger"></span>
        </td>
        <td width="10%">
          <%= daily_status_report.text_field :end_time, value: "#{daily_status_report&.object&.end_time&.strftime("%H:%M") rescue ''}",
                                       placeholder: "End Time",
                                       class: "form-control end_time timer timeEst timer",
                                       required: true, readonly: true, data: { target: "dsr.endTime", action: "blur->dsr#validateValue" } %>
          <span class="text-danger"></span>
        </td>

        <td width="10%">
          <% if add_sub %>
            <%= link_to("javascript:void(0)", class: "btn btn-warning btn-sm btn-circle add-task", data: { action: "click->dsr#add_sub_association", "dsr-project-param" => project_id || 0 }) do %>
              <i class="fa fa-plus" aria-hidden="true"></i>
            <% end %>
          <% elsif daily_status_report&.object&.id.nil? %>
            <%= link_to("javascript:void(0)", class: "btn btn-danger btn-sm btn-circle remove-task", data: { action: "click->dsr#remove_sub_association" }) do %>
              <i class="fa fa-times" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </td>
      </tr>

      <tr id="tr-3">
        <td colspan="3">
          <%= daily_status_report.text_area :description, placeholder: "Description", class: "form-control dsr dsr-area", required: true, data: { target: "dsr.description" , action: "blur->dsr#validateValue" } %>
          <span class="text-danger"></span>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
<% else %>
  <tbody id="nested-sub-fields" class="sub-table-body">
  <tr id="tr-1">
    <%= daily_status_report.hidden_field :_destroy %>
  </tr>
  <tr id="tr-2">
    <td width="70%">
      <%= daily_status_report.text_field :task, placeholder: "Task", class: "form-control dsr", required: true, data: { target: "dsr.task" , action: "blur->dsr#validateValue" } %>
      <span class="text-danger"></span>
    </td>

    <td width="10%">
      <%= daily_status_report.text_field :start_time, value: "#{daily_status_report&.object&.start_time&.strftime("%H:%M") rescue ''}",
                                   placeholder: "Start Time",
                                   class: "form-control start_time timer timeEst timer",
                                   required: true, readonly: true, data: { target: "dsr.startTime", action: "blur->dsr#validateValue" } %>
      <span class="text-danger"></span>
    </td>
    <td width="10%">
      <%= daily_status_report.text_field :end_time, value: "#{daily_status_report&.object&.end_time&.strftime("%H:%M") rescue ''}",
                                   placeholder: "End Time",
                                   class: "form-control end_time timer timeEst timer",
                                   required: true, readonly: true, data: { target: "dsr.endTime", action: "blur->dsr#validateValue" } %>
      <span class="text-danger"></span>
    </td>

    <td width="10%">
      <% if add_sub %>
        <%= link_to("javascript:void(0)", class: "btn btn-warning btn-sm btn-circle add-task", data: { action: "click->dsr#add_sub_association", "dsr-project-param" => project_id || 0 }) do %>
          <i class="fa fa-plus" aria-hidden="true"></i>
        <% end %>
      <% elsif daily_status_report&.object&.id.nil? %>
        <%= link_to("javascript:void(0)", class: "btn btn-danger btn-sm btn-circle remove-task", data: { action: "click->dsr#remove_sub_association" }) do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </td>
  </tr>

  <tr id="tr-3">
    <td colspan="3">
      <%= daily_status_report.text_area :description, placeholder: "Description", class: "form-control dsr dsr-area", required: true, data: { target: "dsr.description", action: "blur->dsr#validateValue" } %>
      <span class="text-danger"></span>
    </td>
  </tr>
  </tbody>
<% end %>

app/views/dsr/add_comment.js.erb
$("#dsr-comments-text-<%= @dsr.id %>-<%= @dsr.user_id %>").val("");
$("#no-comments-<%= @dsr.id %>-<%= @dsr.user_id %>")?.remove();

app/views/dsr/comments.js.erb
$("#dsr-comments").html("<%= j render(partial: "dsr/comment_form", locals: { dsr: @dsr, current_user: current_user}) %>");

app/views/dsr/received_dsr.html.erb
<div id="dsr-receive-table-div">
  <%= render partial: "dsr/dsr", locals: { dsrs: @dsrs, pagy: @pagy, dsr: @dsr, current_user: current_user} %>
</div>

app/views/dsr/received_dsr.js.erb
$('#loader-body').fadeOut();
$("#dsr-receive-table-div").html("<%= j render(partial: "dsr/dsr", locals: { dsrs: @dsrs, pagy: @pagy, dsr: @dsr, current_user: current_user}) %>");

app/views/dsr/send_dsr.html.erb
<div id="send-dsr-div">
  <%= render partial: "dsr/dsr", locals: { dsrs: @dsrs, pagy: @pagy, dsr: @dsr, current_user: current_user} %>
</div>

app/views/dsr/send_dsr.js.erb
$('#loader-body').fadeOut();
$("#send-dsr-div").html("<%= j render(partial: "dsr/dsr", locals: { dsrs: @dsrs, pagy: @pagy, dsr: @dsr, current_user: current_user}) %>");